// Regenerates `lib/tools/ui/heroicons.g.dart` from a checkout of the
// `heroicons` package.
//
// The published package carries 1288 SVGs — five megabytes — of which this app
// draws about eighty. On a mobile app that only costs disk, but on the web
// every one of those files is an entry in `AssetManifest.bin.json`, which is
// downloaded and parsed before the first frame, and every icon that does get
// drawn is a separate HTTP request. Compiling the handful we use straight into
// the bundle removes both costs.
//
// Usage:
//   dart run tool/gen_heroicons.dart [--source <path to heroicons/assets>]
//
// The set of icons is derived from `lib/`, so adding a `HeroIcons.foo` to the
// app and re-running this is all that is needed. Styles other than outline have
// to be declared in `tool/heroicons.yaml`.
import 'dart:io';

const _config = 'tool/heroicons.yaml';
const _output = 'lib/tools/ui/heroicons.g.dart';

void main(List<String> args) {
  final sourceOverride = _flag(args, '--source');
  final config = _readConfig();
  final source = Directory(_expandHome(sourceOverride ?? config.source));
  if (!source.existsSync()) {
    _fail(
      'No icon source at ${source.path}.\n'
      'Point `source:` in $_config at a copy of the heroicons package, or pass '
      '--source.',
    );
  }

  final used = _scanUsedIcons();
  if (used.isEmpty) _fail('Found no `HeroIcons.<name>` references in lib/.');
  stdout.writeln('${used.length} icons referenced by lib/');

  final buffer = StringBuffer()
    ..writeln(
      '// GENERATED BY `dart run tool/gen_heroicons.dart` — do not edit.',
    )
    ..writeln('//')
    ..writeln(
      '// The icon set is derived from the `HeroIcons.<name>` references in lib/;',
    )
    ..writeln('// extra styles come from tool/heroicons.yaml.')
    ..writeln()
    ..writeln(
      '/// The subset of https://heroicons.com that this app draws, inlined so that',
    )
    ..writeln('/// no icon costs an asset-manifest entry or an HTTP request.')
    ..writeln('enum HeroIcons {');

  for (final name in used) {
    final outline = _load(source, 'outline', name);
    final solid = config.solid.contains(name)
        ? _load(source, 'solid', name)
        : null;
    buffer.writeln('  $name(');
    buffer.writeln("    outline: '$outline',");
    if (solid != null) buffer.writeln("    solid: '$solid',");
    buffer.writeln('  ),');
  }

  buffer
    ..writeln('  ;')
    ..writeln()
    ..writeln('  const HeroIcons({required this.outline, this.solid});')
    ..writeln()
    ..writeln('  /// The default style, always generated.')
    ..writeln('  final String outline;')
    ..writeln()
    ..writeln('  /// Only generated for the icons listed under `solid:` in')
    ..writeln('  /// tool/heroicons.yaml, and null for all the others.')
    ..writeln('  final String? solid;')
    ..writeln('}');

  File(_output).writeAsStringSync(buffer.toString());
  stdout.writeln('wrote $_output (${File(_output).lengthSync()} bytes)');
  final format = Process.runSync('dart', ['format', _output]);
  stdout.write(format.stdout);
}

/// Every `HeroIcons.<name>` mentioned anywhere under lib/, sorted so that the
/// generated file only changes when the icon set does.
List<String> _scanUsedIcons() {
  final pattern = RegExp(r'HeroIcons\.([a-zA-Z][a-zA-Z0-9]*)');
  final names = <String>{};
  for (final entity in Directory('lib').listSync(recursive: true)) {
    if (entity is! File || !entity.path.endsWith('.dart')) continue;
    if (entity.path.endsWith('heroicons.g.dart')) continue;
    for (final match in pattern.allMatches(entity.readAsStringSync())) {
      names.add(match.group(1)!);
    }
  }
  // `values` is the only member reachable through the same prefix.
  names.remove('values');
  return names.toList()..sort();
}

/// Reads one SVG and reduces it to a single-line Dart string literal.
///
/// The `width`/`height` attributes are dropped because [HeroIcon] always sets
/// its own, and the `viewBox` is what actually scales the geometry.
String _load(Directory source, String style, String name) {
  final file = File('${source.path}/$style/${_kebab(name)}.svg');
  if (!file.existsSync()) {
    _fail(
      'HeroIcons.$name has no $style variant at ${file.path}.\n'
      'Either the icon was renamed upstream or the source tree is incomplete.',
    );
  }
  final raw = file.readAsStringSync().replaceAll(RegExp(r'\s*\n\s*'), '');
  final body = RegExp(
    r'^<svg[^>]*>(.*)</svg>\s*$',
    dotAll: true,
  ).firstMatch(raw)?.group(1);
  if (body == null) _fail('${file.path} is not a single <svg> element.');
  return '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" '
          'fill="none">$body</svg>'
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$');
}

String _kebab(String camel) => camel
    .replaceAllMapped(RegExp(r'(?<=[a-z0-9])[A-Z]'), (m) => '-${m[0]}')
    .toLowerCase();

({String source, Set<String> solid}) _readConfig() {
  // A three-key file does not justify pulling in a YAML parser.
  final lines = File(_config).readAsLinesSync();
  var source = '';
  final solid = <String>{};
  var inSolid = false;
  for (final line in lines) {
    final trimmed = line.trim();
    if (trimmed.isEmpty || trimmed.startsWith('#')) continue;
    if (trimmed.startsWith('- ')) {
      if (inSolid) solid.add(trimmed.substring(2).trim());
      continue;
    }
    inSolid = trimmed == 'solid:';
    if (trimmed.startsWith('source:')) {
      source = trimmed.substring('source:'.length).trim();
    }
  }
  if (source.isEmpty) _fail('No `source:` in $_config.');
  return (source: source, solid: solid);
}

String _expandHome(String path) => path.startsWith('~/')
    ? '${Platform.environment['HOME']}${path.substring(1)}'
    : path;

String? _flag(List<String> args, String name) {
  final i = args.indexOf(name);
  return i >= 0 && i + 1 < args.length ? args[i + 1] : null;
}

Never _fail(String message) {
  stderr.writeln(message);
  exit(1);
}
